todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('auth/', include('users.urls')),
    path("", include("todo_app.urls")),
]

todo/todo_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.ListListView.as_view(), name="index"),
    path('add/', views.add_task, name='add'),
    path('view/', views.view_tasks, name='view'),
    path('time_tracker/all/', views.time_tracker, name='time_tracker'),
    path('time_tracker/new/', views.add_tracker, name='add_tracker'),
    path('time_tracker/<slug:slug>/', views.tracker_profile, name='tracker_profile'),
]

todo/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

todo/todo_app/models.py
from django.db import models
from django.contrib.auth import get_user_model
from .helpers import slugify

User = get_user_model()


class ToDoList(models.Model):
    title = models.CharField(max_length=80, unique=True)

    def __str__(self):
        return self.title


class ToDoItem(models.Model):
    title = models.CharField(
        max_length=80, verbose_name='Название'
    )
    description = models.TextField(
        null=True, blank=True, verbose_name='Описание'
    )
    due_date = models.DateTimeField(
        verbose_name='Выберите дату события'
    )
    todo_list = models.ForeignKey(
        ToDoList, on_delete=models.CASCADE,
        null=True, blank=True, verbose_name='Выберите список дел'
    )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE
    )

    class Meta:
        ordering = ["-due_date"]

    def __str__(self):
        return self.title


class TimeTracker(models.Model):
    task = models.CharField(
        max_length=80, verbose_name='Название'
    )
    slug = models.SlugField()
    final_time = models.IntegerField(default=0)
    description = models.TextField(
        null=True, blank=True, verbose_name='Описание'
    )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE,
    )
    counting = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.task)

        super(TimeTracker, self).save(*args, **kwargs)

    def __str__(self):
        return self.task

todo/todo_app/forms.py
from django import forms

from .models import ToDoItem, TimeTracker


class ToDoItemPost(forms.ModelForm):

    class Meta:
        model = ToDoItem
        fields = ['title', 'description', 'due_date', 'todo_list',]
        widgets = {
            'description': forms.Textarea
        }


class TimeTrackerForm(forms.ModelForm):

    class Meta:
        model = TimeTracker
        fields = ['task', 'description',]
        widgets = {
            'description': forms.Textarea
        }

todo/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

todo/todo_app/views.py
import json
import time
from datetime import date

from django.core.paginator import Paginator
from django.db.models import F
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView
from .models import ToDoList, ToDoItem, TimeTracker
from .forms import ToDoItemPost, TimeTrackerForm


class ListListView(ListView):
    model = ToDoList
    template_name = "todo_app/index.html"


def make_paginator(request, object, pages):
    paginator = Paginator(object, pages)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def add_task(request):
    template = 'todo_app/add_task.html'
    form = ToDoItemPost(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            return redirect('/')
    context = {
        'form': form
    }
    return render(request, template, context)


def view_tasks(request):
    tasks = ToDoItem.objects.all().filter(user=request.user)
    page_obj = make_paginator(request, tasks, 5)
    today_day = date.today()
    template = 'todo_app/view_task.html'
    context = {
        'page_obj': page_obj,
        'today_day': today_day
    }
    return render(request, template, context)


def time_tracker(request):
    template = 'todo_app/view_trackers.html'
    user = request.user
    track = TimeTracker.objects.all().filter(user=user)
    page_obj = make_paginator(request, track, 4)
    context = {
        'page_obj': page_obj,
        'track': track,
    }
    return render(request, template, context)


def add_tracker(request):
    template = 'todo_app/add_tracker.html'
    form = TimeTrackerForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            track = form.save(commit=False)
            track.user = request.user
            track.save()
            return redirect('/')

    context = {
        'form': form
    }
    return render(request, template, context)


def tracker_profile(request, slug):
    template = 'todo_app/one_tracker.html'
    track = get_object_or_404(TimeTracker, slug=slug)
    form = TimeTrackerForm(
        request.POST or None,
        files=request.FILES or None,
        instance=track
    )

    if request.method == "POST":
        post_data = json.loads(request.body.decode("utf-8"))
        sec = int(post_data['sec'])
        min = int(post_data['min']) * 60
        TimeTracker.objects.filter(slug=slug).update(final_time=F('final_time') + sec + min)
    ty_res = time.gmtime(track.final_time)
    res = time.strftime("%d:%H:%M:%S", ty_res)
    context = {
        'track': track,
        'form': form,
        'res': res
    }
    return render(request, template, context)

todo/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('index')
    template_name = 'users/signup.html'

todo/todo_app/templates/base.html
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
  <body>
      {% include 'includes/header.html' %}
    <main>
      <div class="container py-5">
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
  {% include 'includes/footer.html' %}
  </body>
</html>

todo/todo_app/templates/includes/footer.html
<footer align="right">
  <p>© 2022 Copyright <span style="color:green">To</span>Do</p>
</footer>

todo/todo_app/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: green">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}">
        Главная
      </a>

{% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-pills">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" style="color:white" href="{% url 'add' %}">Новое дело</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="color:white" href="{% url 'add_tracker' %}">Новый трекер</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link link-light
          {% if view_name  == 'users:login' %}
          active
          {% endif %}"
             href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light
          {% if view_name  == 'users:signup' %}
          active
          {% endif %}"
             href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
      {% endwith %}
      {# Конец добавленого в спринте #}
    </div>
  </nav>
</header>

todo/todo_app/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation"  class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item" style="color:green"><a class="page-link" style="color:green" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" style="color:green" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item disabled" style="color:green">
            <span class="page-link" style="color:green">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" style="color:green" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item" >
        <a class="page-link" style="color:green" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item" style="color:green">
        <a class="page-link" style="color:green" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

todo/todo_app/templates/todo_app/add_task.html
{% extends 'base.html' %}

{% block content %}
    <h1>Новое событие</h1>
    <form method="POST" class="post-form">
        <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                    <label for="id_text">
                    </label>
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group row my-3 p-3">
                    {{ field.label_tag }}
                    {{ field }}
                    <small id="id_text-help" class="form-text text-muted">
                      {{ field.help_text }}
                    </small>
                    </div>
                    {% endfor %}
        <button type="submit" class="btn btn-light" value="Submit">Save</button>
    </form>
{% endblock %}

todo/todo_app/templates/todo_app/add_tracker.html
{% extends 'base.html' %}

{% block content %}
<title>Новый трекер</title>
    <h1>Новый трекер</h1>
    <form method="POST" class="post-form">
        <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                    <label for="id_text">
                    </label>
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group row my-3 p-3">
                    {{ field.label_tag }}
                    {{ field }}
                    <small id="id_text-help" class="form-text text-muted">
                      {{ field.help_text }}
                    </small>
                    </div>
                    {% endfor %}
        <button type="submit" class="btn btn-light" value="Submit">Save</button>
    </form>
{% endblock %}

todo/todo_app/templates/todo_app/index.html
{% extends 'base.html' %}
{% block content %}
<title>Добро пожаловать!</title>

    <div class="container d-flex justify-content-center align">
          <span class="fs-1">Выбери</span>
    </div>
<div style="text-align:center">
     <button type="button" class="btn btn-light">
         <a href="{% url 'add'  %}">
             Добавить событие
         </a>
     </button>
     <button type="button" class="btn btn-light">
          <a href="{% url 'view'  %}">Посмотреть события</a>
     </button>
    <button type="button" class="btn btn-light">
          <a href="{% url 'add_tracker'  %}">Добавить новый трекер</a>
     </button>
    <button type="button" class="btn btn-light">
          <a href="{% url 'time_tracker'  %}">Отслеживать время</a>
     </button>
</div>
{% endblock %}

todo/todo_app/templates/todo_app/one_tracker.html
{% extends 'base.html' %}
{% block content %}
<title>
    Трекер дел
</title>

<h1>Ваши дела!</h1>
<div class="container py-5">
    <h2>
            {{ track.task }}
    </h2>
<form method="post">{% csrf_token %}
<p id="secundomer"></p>
    <input type="button" value="старт" onclick="start()" />
    <input type="button" value="стоп" onclick="stop()" />
    <input type="button" value="сброс" onclick="cancel()" />

    <script>
        var ms = 0;   //мс
       var s = 0;    //сек
       var m = 0;    //мин
       var MS = 0;   //мс
       var S = 0;    //сек
       var M = 0;    //мин
       var SM = document.getElementById("secundomer");


           function fstart() {
                        ms++;
                   if (ms == 1) {
                       ms = 0;
                       s += 1;
                   }
                   if (s == 60) {
                       s = 0;
                       m += 1;
                   }
                   if (m == 60) {
                       clearInterval(x);
                   }
                   MS = "00";
                   if (ms > 99)
                       MS = (ms - (ms % 10)) / 10;
                   if (ms > 9)
                       MS = "0" + (ms-(ms%10))/10;
                   if (s < 10)
                       S = "0" + s;
                   else
                       S = s;
                   if (m < 10)
                       M = "0" + m;
                   else
                       M = m;
                   SM.innerHTML = MS + ":" + S + ":" + M;
           }

           var x;
           function start() { x = setInterval(fstart, 1);
            }

        function stop()
        { data = JSON.stringify({
    sec : s,
    min : m
})
        fetch('http://127.0.0.1:8000/time_tracker/beg/', {
    method: 'POST',
    headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
    },
     body: data,
  });
            clearInterval(x);
        }

        function cancel()
        {
            clearInterval(x);
            ms = 0;
            s = 0;
            m = 0;
            SM.innerHTML = MS + ":" + S + ":" + M;
        }


    </script>

</div>
    </h2>

       <hr>
{% if track.description %}
<li>
      Описание: {{ track.description  }}
    </li>
{% endif %}
    <li>
        Всего времени: {{ res }}

    </li>

{% endblock %}

todo/todo_app/templates/todo_app/view_task.html
{% extends 'base.html' %}
{% block content %}
<title>
        Ваши дела!
    </title>
<h1>Ваши дела!</h1>
{% for task in page_obj %}
{% if today_day|date:"Y-m-d" < task.due_date|date:"Y-m-d" %}
<div class="container py-5">
    <h2>{{ task.title }} </h2>
       <hr>
<li>
    Время {{ task.due_date|date:"d E Y"  }}
</li>
    {% if task.description %}
<li>
    Описание: {{ task.description }}
</li>
    {% endif %}
    {% if task.todo_list %}
<li>
    Группа событий: {{ task.todo_list }}
</li>
{% endif %}
</div>
{% endif %}
{% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %}

todo/todo_app/templates/todo_app/view_trackers.html
{% extends 'base.html' %}
{% block content %}
<title>
    Трекер дел
</title>
<h1>Ваши дела!</h1>
<div class="container py-5">
    {% for task in page_obj%}
    <h2>
        <a href="{% url 'tracker_profile' task.slug %}">
            {{ task.task }}
        </a>
    </h2>
       <hr>
    <li>
      Описание: {{ task.description  }}
    </li>
    <li>
        Всего времени: {{ task.final_time }}
    </li>

    {% endfor%}

</div>
{% endblock %}

{% include 'includes/paginator.html' %}

todo/todo_app/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

todo/todo_app/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %}
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-success">
              Войти
            </button>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

todo/todo_app/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-success">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}